name: Deploy to Server

on:
  push:
    branches:
      - main  # Se déclenche quand tu pousses sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement via SSH (rsync)
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: . # On prend tout le dossier actuel
          remote_path: /var/www/html # TON DOSSIER SUR LE SERVEUR (à adapter si besoin)
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
